name: Validate Composer files

on: [push]

jobs:
  validate_composer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Cache Composer dependencies
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Validate dependencies
        uses: php-actions/composer@v6.1.2
        with:
          command: validate
          php_version: "8.2.0"