name: Validate Composer files

on: [push]

jobs:
  validate_composer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Cache Composer dependencies
        uses: actions/cache@v5.1.0
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Validate dependencies
        uses: php-actions/composer@v6.1.2
        with:
          command: validate
          php_version: "8.2.0"